### ISSUE TITLE
(SP: 3) Email verification error

### ISSUE THREAD

**Issue by asya982** [ita-social-projects/SpaceToStudy-Client#1686]
After registration go to email verification list
This link will redirect to error that your email was already verified

After log out from account A and new sign up an account B verification link is automatically loged in account A and error "Token is invalid" is displayed
### Deeper investigation needed
![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/105641724/c7099a9f-3fad-41e9-9b67-3f0fc5708d5d)

**Comment by GeorgeShvab** [comment]
Email verification UI works incorrectly because the client makes two requests to the server.
The first request confirms email, and the second request always returns error because email was already confirmed by the first request. As far as I investigated, requests are made two times because of React strict mode, as it runs each effect two times.

I also tested verification on the deployed version, local build and without React strict mode. It works correctly in those cases, cause strict mode works only in development mode. I also tested backend email verification logic, there are no problems, so that is only front-end issue.

I guess that is not a bug, as it is a desired behaviour of React strict mode and it appears only in development mode.

Here are screenshots from the deployed version, local build and without strict mode, everything works well there.

![email-bug-deployed](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/62070431/77d94ca7-2db4-4471-b66f-56997af01c14)
![email-bug-without-strict](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/62070431/11499b6c-31f1-4182-adb0-03643fa96e27)
