### ISSUE TITLE
(SP:) [Cooperation] Cannot create an activity from a course template

### ISSUE THREAD

**Issue by iva-stasia** [ita-social-projects/SpaceToStudy-Client#1868]
The bug occurs when trying to create an activity from a course template. blocked by #1873 

<img width="853" alt="image" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/110097862/99527b79-1782-4d87-a881-05559b424d54">

<img width="1625" alt="image" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/110097862/df08a09c-16fc-4215-ab15-346a63b53dc2">

**Comment by GeorgeShvab** [comment]
I conducted some investigation and it looks like this bug has not been present anymore since #1873. The bug started to appear after #1842, when `CooperationProvider` was moved below `ModalProvider`. As a result, modals lost access to `cooperationContext` and its functions like `setIsActivityCreated`, `setSelectedCourse` and `setIsAddedClicked`. The functions became undefined inside of modal and that is why error `setSelectedCourse is not a function` appeared. In #1873 `cooperationContext` was replaced by redux toolkit and the bug disappeared, as redux wraps entire app.
