### ISSUE TITLE
(SP: 2) Investigate new chat implementation (spike)

### ISSUE THREAD

**Issue by mhevyk** [ita-social-projects/SpaceToStudy-Client#1892]
Current implementation of chat is not very suitable for our project needs. Also it is a source of bugs and stops project progress a lot. I suggest to investigate this question, how can we rewrite chat and what is the best solution that we can implement. Maybe we need to use websockets instead

**Comment by D1nviz** [comment]
So, having studied the packages that can be used to create a chat and more I have chosen **`Socket IO`** as the best option for me. To be honest, we have i think only 2 options. 

1.   Socket.IO
2.   WebSocket

### Socket.IO

`Socket.IO` is a JavaScript library that enables real-time, bidirectional, and event-based communication between the browser and the server. It consists of two parts: a client-side library that runs in the browser and a server-side library for Node.js.

- `Client Side:` The client-side library runs in the browser and provides an API for emitting and listening to events. It automatically handles connection persistence, disconnection detection, and reconnection logic.

  ![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/118522791/4a8c0e27-1f1e-40fd-ae4a-0fadbeb68431)


- `Server Side:` The server-side library is a Node.js application and provides an API for sending and receiving messages to/from clients. It also provides rooms and namespaces for managing multiple communication channels.
 

   ![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/118522791/32b87870-34fa-4951-8f86-bd66acac55ac)

### Advantages:

- Connection management: When a connection is interrupted, Socket.IO automatically attempts to reconnect according to the connection strategy that you decide, such as how long it should wait before trying again and how many reconnection attempts it should make.

- Rooms: Rooms allow you to group multiple clients together in one channel, so you can broadcast a message to all of them with just one call to Socket.IO.

- Multiplexing: Socket.IO’s namespacing lets you divide a single connection into multiple logical connections, which can help you to organize and manage separately the communication for different parts of your application. This is likely to be more resource efficient than running multiple WebSocket connections, especially as it removes the overhead of establishing multiple connections

- Reduces development and maintenance overhead: As a realtime messaging library, Socket.IO takes care of a lot of functionality that you would otherwise have to implement yourself if you were using a pure WebSocket implementation, for example, falling back to HTTP if WebSocket is unavailable, reconnecting disrupted connections automatically, and multiplexing.
### Disadvantages:
 
- Single region: Socket.IO can only run in one datacenter or cloud region. With no fallback, failures at your cloud provider will take your messaging offline. Driving all traffic to a single geographic location also means users further away will experience higher latencies. In cases where uptime and reliability are critical, consider using a realtime PaaS that has a global network, instead.

- Weak message guarantees Socket.IO defaults to 'at most once' delivery. In other words, it promises never to deliver your message more than once - but it doesn't rule out the chance of the message not being delivered at all. That’s largely the same with WebSocket, which relies on TCP’s ordering to deliver messages in order but offers no other guarantees. For anything else, you’ll need to implement it in your application code, whether it’s Socket.IO or WebSocket.

 #### Also i have provided a simple code, that shows you how is easy to use Socket.IO
`Server.js:`


``` 
const express = require('express');
const http = require('http');
const socketIo = require('socket.io');

const app = express();
const server = http.createServer(app);
const io = socketIo(server);

app.use(express.static('public'));

io.on('connection', (socket) => {
    console.log('New client connected');

    socket.on('chat message', (msg) => {
        io.emit('chat message', msg);
    });

    socket.on('disconnect', () => {
        console.log('Client disconnected');
    });
});

server.listen(3000, () => {
    console.log('Server is running on port 3000');
}) 
```

`Client.js:`
```
import React, { useState, useEffect } from 'react';
import io from 'socket.io-client';

const socket = io('http://localhost:3000');

const Chat = () => {
    const [messages, setMessages] = useState([]);
    const [input, setInput] = useState('');

    useEffect(() => {
        socket.on('chat message', (msg) => {
            setMessages((prevMessages) => [...prevMessages, msg]);
        });

        return () => {
            socket.off('chat message');
        };
    }, []);

    const sendMessage = () => {
        socket.emit('chat message', input);
        setInput('');
    };

    return (
        <div>
            <h1>Chat Application</h1>
            <div>
                {messages.map((msg, index) => (
                    <div key={index}>{msg}</div>
                ))}
            </div>
            <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
            />
            <button onClick={sendMessage}>Send</button>
        </div>
    );
};

export default Chat; 
```


### About WebSocket
`WebSocket` Wis a standardized protocol that allows for real-time message exchange between clients and servers. It comes with an API that provides access to this protocol. Unlike Socket.IO, which is a comprehensive messaging library, WebSocket is a core web technology maintained by WHATWG, similar to HTML. This means it is supported by all current versions of major web browsers, mobile devices, and backend libraries like ws in the NodeJS ecosystem. Prior to WebSocket, real-time web communication was only possible through methods like HTTP long polling.


#### WebSocket's main characteristics include:

- Bidirectional communication: WebSocket connections are full-duplex, allowing messages to flow in both directions between client and server without interference.

- Continuous connections: WebSocket maintains the connection until it is no longer needed or until an issue like a network problem interrupts it. This changes the way we handle messages, as it becomes a continuous resource.
 
- Broad support: As a web standard technology, WebSocket is widely available in browsers, backend languages, and IoT devices.
 
- Emphasis on discrete message delivery: WebSocket operates in self-contained messages, such as a chat message from one participant to all others in a specific chat group. A message is either delivered or not, contrasting with streaming protocols like WebRTC, where losing individual data parts (like a few video frames) is acceptable if it helps maintain the byte flow.

**Comment by D1nviz** [comment]
# Chat implementation (based on websocket technology)

In this article, I explored websockets and their use. I analyzed many approaches and chose 2 that I liked the most. So grab a cup of tea and let's learn more about these technologies together 🍵😊

1.  `WebSocket`
2.   `Socket.IO`


## About WebSocket
`WebSocket` is a standardized protocol that allows for real-time message exchange between clients and servers. It comes with an API that provides access to this protocol. Unlike Socket.IO, which is a comprehensive messaging library, WebSocket is a core web technology maintained by WHATWG, similar to HTML. This means it is supported by all current versions of major web browsers, mobile devices, and backend libraries like ws in the NodeJS ecosystem. Prior to WebSocket, real-time web communication was only possible through methods like HTTP long polling.


### WebSocket's main characteristics include:

- Bidirectional communication: WebSocket connections are full-duplex, allowing messages to flow in both directions between client and server without interference.

- Continuous connections: WebSocket maintains the connection until it is no longer needed or until an issue like a network problem interrupts it. This changes the way we handle messages, as it becomes a continuous resource.
 
- Broad support: As a web standard technology, WebSocket is widely available in browsers, backend languages, and IoT devices.
 
- Emphasis on discrete message delivery: WebSocket operates in self-contained messages, such as a chat message from one participant to all others in a specific chat group. A message is either delivered or not, contrasting with streaming protocols like WebRTC, where losing individual data parts (like a few video frames) is acceptable if it helps maintain the byte flow.

#### Code example, how to realize chat using WebSocket Protocol
`Server.js:`
```const express = require('express');
const http = require('http');
const WebSocket = require('ws');

const app = express();
const server = http.createServer(app);
const wss = new WebSocket.Server({ server });

app.use(express.static('public'));

wss.on('connection', (ws) => {
    console.log('New client connected');

    ws.on('message', (message) => {
        console.log('Received:', message);
        // Broadcast the message to all clients
        wss.clients.forEach((client) => {
            if (client.readyState === WebSocket.OPEN) {
                client.send(message);
            }
        });
    });

    ws.on('close', () => {
        console.log('Client disconnected');
    });
});

server.listen(3000, () => {
    console.log('Server is running on port 3000');
});
```
`Client.js`

```import React, { useState, useEffect } from 'react';

const Chat = () => {
    const [messages, setMessages] = useState([]);
    const [input, setInput] = useState('');
    const [ws, setWs] = useState(null);

    useEffect(() => {
        const socket = new WebSocket('ws://localhost:3000');
        setWs(socket);

        socket.onmessage = (event) => {
            setMessages((prevMessages) => [...prevMessages, event.data]);
        };

        return () => {
            socket.close();
        };
    }, []);

    const sendMessage = () => {
        if (ws) {
            ws.send(input);
            setInput('');
        }
    };

    return (
        <div>
            <h1>Chat Application</h1>
            <div>
                {messages.map((msg, index) => (
                    <div key={index}>{msg}</div>
                ))}
            </div>
            <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
            />
            <button onClick={sendMessage}>Send</button>
        </div>
    );
};

export default Chat;
```


## Socket.IO

`Socket.IO` is a JavaScript library that enables real-time, bidirectional, and event-based communication between the browser and the server. It consists of two parts: a client-side library that runs in the browser and a server-side library for Node.js.

- `Client Side:` The client-side library runs in the browser and provides an API for emitting and listening to events. It automatically handles connection persistence, disconnection detection, and reconnection logic.

  ![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/118522791/4a8c0e27-1f1e-40fd-ae4a-0fadbeb68431)


- `Server Side:` The server-side library is a Node.js application and provides an API for sending and receiving messages to/from clients. It also provides rooms and namespaces for managing multiple communication channels.
 

   ![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/118522791/32b87870-34fa-4951-8f86-bd66acac55ac)

### Advantages:

- Connection management: When a connection is interrupted, Socket.IO automatically attempts to reconnect according to the connection strategy that you decide, such as how long it should wait before trying again and how many reconnection attempts it should make.

- Rooms: Rooms allow you to group multiple clients together in one channel, so you can broadcast a message to all of them with just one call to Socket.IO.

- Multiplexing: Socket.IO’s namespacing lets you divide a single connection into multiple logical connections, which can help you to organize and manage separately the communication for different parts of your application. This is likely to be more resource efficient than running multiple WebSocket connections, especially as it removes the overhead of establishing multiple connections

- Reduces development and maintenance overhead: As a realtime messaging library, Socket.IO takes care of a lot of functionality that you would otherwise have to implement yourself if you were using a pure WebSocket implementation, for example, falling back to HTTP if WebSocket is unavailable, reconnecting disrupted connections automatically, and multiplexing.
### Disadvantages:
 
- Single region: Socket.IO can only run in one datacenter or cloud region. With no fallback, failures at your cloud provider will take your messaging offline. Driving all traffic to a single geographic location also means users further away will experience higher latencies. In cases where uptime and reliability are critical, consider using a realtime PaaS that has a global network, instead.

- Weak message guarantees Socket.IO defaults to 'at most once' delivery. In other words, it promises never to deliver your message more than once - but it doesn't rule out the chance of the message not being delivered at all. That’s largely the same with WebSocket, which relies on TCP’s ordering to deliver messages in order but offers no other guarantees. For anything else, you’ll need to implement it in your application code, whether it’s Socket.IO or WebSocket.

 #### Also i have provided a simple code, that shows you how is easy to use Socket.IO
`Server.js:`


``` 
const express = require('express');
const http = require('http');
const socketIo = require('socket.io');

const app = express();
const server = http.createServer(app);
const io = socketIo(server);

app.use(express.static('public'));

io.on('connection', (socket) => {
    console.log('New client connected');

    socket.on('chat message', (msg) => {
        io.emit('chat message', msg);
    });

    socket.on('disconnect', () => {
        console.log('Client disconnected');
    });
});

server.listen(3000, () => {
    console.log('Server is running on port 3000');
}) 
```

`Client.js:`
```
import React, { useState, useEffect } from 'react';
import io from 'socket.io-client';

const socket = io('http://localhost:3000');

const Chat = () => {
    const [messages, setMessages] = useState([]);
    const [input, setInput] = useState('');

    useEffect(() => {
        socket.on('chat message', (msg) => {
            setMessages((prevMessages) => [...prevMessages, msg]);
        });

        return () => {
            socket.off('chat message');
        };
    }, []);

    const sendMessage = () => {
        socket.emit('chat message', input);
        setInput('');
    };

    return (
        <div>
            <h1>Chat Application</h1>
            <div>
                {messages.map((msg, index) => (
                    <div key={index}>{msg}</div>
                ))}
            </div>
            <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
            />
            <button onClick={sendMessage}>Send</button>
        </div>
    );
};

export default Chat; 
```


## Conclusion
Both WebSocket and Socket.IO are powerful technologies for building real-time, bidirectional communication applications, such as chat applications. However, they cater to slightly different needs and come with their own sets of advantages and disadvantages.

### Choosing Between WebSocket and Socket.IO

#### Use WebSocket if:

- You need a lightweight, low-level protocol for real-time communication.
- You are comfortable implementing reconnection logic, fallbacks, and other features manually.
- You require broad support across different platforms and devices.

#### Use Socket.IO if:

- You prefer a higher-level library that handles many of the complexities of real-time communication for you.
- You need features like automatic reconnection, rooms, and namespaces.
- You are building an application where ease of development and maintenance is a priority.

#### Thank you for your attention. I hope this small effort has been helpful to you and has assisted with this difficult decision 😊

**Comment by asya982** [comment]
Thank you for this investigation! Information is really great! Nice work!
I think for this project where we mainly studying new technologies and empowering our knowledge it would be more suitable to choose **WebSocket**, so we how it's should be implemented under the hood
So when we are comfortable with WebSocket it will be a piece of cake to move to **Socket.IO** in future work
