### ISSUE TITLE
(SP: 2) Fix lesson icon

### ISSUE THREAD

**Issue by abalanovsky** [ita-social-projects/SpaceToStudy-Client#2024]
Fix lesson icon in the cooperation

<img width="1495" alt="Знімок екрана 2024-07-01 о 14 59 43" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/108689551/4b544320-54cb-4333-90a1-3af3ea326a0a">

**Comment by docia** [comment]
I've tried to recreate the bug, but the test lessons icons are displayed with a proper icon on my side. @abalanovsky  can you test it again, please? if the bug is confirmed, can you provide steps on what you've done that the wrong icon displays?

<img width="875" alt="Screenshot 2024-07-03 at 19 31 38" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/102433497/77f39981-3515-4438-881b-cfa61cc4bcd4">
