### ISSUE TITLE
[Edit profile. Professional info]The categories are displayed without their corresponding category icons.

### ISSUE THREAD

**Issue by YuliaHurska** [ita-social-projects/SpaceToStudy-Client#2802]
**Description:** 
The categories are displayed without their corresponding category icons across all parts of the site.

**Environment:**
1. OS - Windows 10 IoT Enterprise LTSC
2. Browser - Chrome 130.0.6723.117

**Reproducible:** alway

**Preconditions:**
1. Add all categories with one of their subject to 'Edit profile'  page in 'Professional information' block.
2. Click 'Update' button on 'Edit profile' page
3. Reload the page.

**Actual Result:**
Not all the categories have their corresponding category icons.
Only 'Biology' , 'Cooking', 'History', 'IT' : have their corresponding category icons.
![image](https://github.com/user-attachments/assets/0f4e0a51-d83e-4d78-97f0-fb9913aa41c7)
![image](https://github.com/user-attachments/assets/d519ab27-75d5-4381-b5ad-80ca786095b1)
On 'Categories' page:
![image](https://github.com/user-attachments/assets/471f3310-54f8-471b-8e57-d4be239a4368)

**Expected result:**
All of saved categories has a different icon and colour according to the following mock-up.
https://www.figma.com/design/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=19195-62022&t=yrhbYQ08xvSCey0a-1

User story link :
User Story - #2694 
User Story - #2695
TC - #2817

**Comment by sandrvvu** [comment]
Icons were displaying wrong, because the icon field in the categories table in the database has incorrect values.
The db was updated.

Categories pages:
![image](https://github.com/user-attachments/assets/90bea5ec-d242-409c-ad01-883055bcb61a)
Professional information page:
![image](https://github.com/user-attachments/assets/dafed05c-d431-483a-a684-2a5cb0c93ccd)
