### ISSUE TITLE
[Edit profile. Profile] 'Update' button in 'Edit profile' is not disabled after entering invalid data in 'Native Language' field

### ISSUE THREAD

**Issue by OleksandraBondarenko** [ita-social-projects/SpaceToStudy-Client#2804]
**Environment**
1. Google Chrome version 130.0.6723.92 (official build), (arm64)
2. MacBook Air M1, 2020. macOS Sequoia, v15.0.1

**Reproducible**: frequently

Preconditions:
1. The user logged is as a tutor/ student
2. The 'Edit Profile' page is open

Steps to reproduce:
1. Click on the 'Your native language' field
2. Type 'укра'

Actual result:
'Update' button on the top of the 'Edit Profile' is not disabled and is clickable.
Confirmation message 'Success! Your data has been updated’ appeared.

https://github.com/user-attachments/assets/add56411-c397-49e9-92c2-99ced38e2806

https://github.com/user-attachments/assets/6a0cacff-959a-4013-bc11-fe0282554fe3

Expected result:
'Update' button on the top of the 'Edit Profile is disabled and not clickable. 

https://github.com/user-attachments/assets/949653b1-9387-40f8-aeed-dc58a3bb784a

User Story: #2693 
Test Case: #2733

**Comment by Renatavl** [comment]
Input changes its value only when you select a value from dropdown menu. Entering of symbols is just a search within the dropdown menu and it doesn't change any values in the form, that's why "Submit" button is active. If we take away focus from input it returns to that value before entering symbols.
